use KrunalDhote351

create table Country(
	Id int primary key identity(101,1),
	CountryName varchar(250) not null unique
)
drop table Country
--Country
INSERT INTO Country(CountryName) VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo, Democratic Republic of the'),
('Congo, Republic of the'),
('Costa Rica'),
('Cote d''Ivoire'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Eswatini'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Kosovo'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('North Korea'),
('North Macedonia'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Palestine'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Korea'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States of America'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City (Holy See)'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe');

--Maharashtra
state
create table State(
	Id int primary key identity(101,1),
	StateName varchar(250) unique not null,
	CountryId int not null
)

INSERT INTO State (StateName,CountryId) VALUES
('Andhra Pradesh',177),
('Arunachal Pradesh',177),
('Assam',177),
('Bihar',177),
('Chhattisgarh',177),
('Goa',177),
('Gujarat',177),
('Haryana',177),
('Himachal Pradesh',177),
('Jharkhand',177),
('Karnataka',177),
('Kerala',177),
('Madhya Pradesh',177),
('Maharashtra',177),
('Manipur',177),
('Meghalaya',177),
('Mizoram',177),
('Nagaland',177),
('Odisha',177),
('Punjab',177),
('Rajasthan',177),
('Sikkim',177),
('Tamil Nadu',177),
('Telangana',177),
('Tripura',177),
('Uttar Pradesh',177),
('Uttarakhand',177),
('West Bengal',177);


Create Table City(
	Id int primary key identity(101,1),
	CityName varchar(250) not null,
	CountryId int not null,
	StateId int not null
)
drop table City
INSERT INTO City VALUES
('Mumbai',177,114),
('Pune',177,114),
('Nagpur',177,114),
('Thane',177,114),
('Nashik',177,114),
('Aurangabad',177,114),
('Solapur',177,114),
('Kolhapur',177,114),
('Amravati',177,114),
('Latur',177,114),
('Sangli-Miraj & Kupwad',177,114),
('Jalgaon',177,114),
('Ahmednagar',177,114),
('Akola',177,114),
('Chandrapur',177,114),
('Parbhani',177,114),
('Bhusawal',177,114),
('Malegaon',177,114),
('Osmanabad',177,114),
('Nanded',177,114),
('Ichalkaranji',177,114),
('Panvel',177,114),
('Satara',177,114),
('Beed',177,114),
('Yavatmal',177,114),
('Ratnagiri',177,114);

--Bihar
INSERT INTO City 
VALUES ('Patna',177,104),
       ('Gaya',177,104),
       ('Bhagalpur',177,104),
       ('Muzaffarpur',177,104),
       ('Darbhanga',177,104),
       ('Purnia',177,104),
       ('Aurangabad',177,104),
       ('Katihar',177,104),
       ('Sasaram',177,104),
       ('Arrah',177,104);

INSERT INTO city
VALUES ('Ahmedabad',177,107),
       ('Surat',177,107),
       ('Vadodara',177,107),
       ('Rajkot',177,107),
       ('Bhavnagar',177,107),
       ('Jamnagar',177,107),
       ('Junagadh',177,107),
       ('Anand',177,107),
       ('Navsari',177,107),
       ('Morbi',177,107);

INSERT INTO city
VALUES ('Bhopal',177,113),
       ('Indore',177,113),
       ('Jabalpur',177,113),
       ('Gwalior',177,113),
       ('Ujjain',177,113),
       ('Sagar',177,113),
       ('Ratlam',177,113),
       ('Khandwa',177,113),
       ('Chhindwara',177,113),
       ('Burhanpur',177,113);

--Jharkhand
INSERT INTO city
VALUES
('Ranchi',177,110),
('Dhanbad',177,110),
('Jamshedpur',177,110),
('Bokaro Steel City',177,110),
('Hazaribagh',177,110),
('Deoghar',177,110),
('Giridih',177,110),
('Ramgarh',177,110),
('Medininagar',177,110),
('Chirkunda',177,110);
--Karnataka
INSERT INTO city
VALUES ('Bangalore',177,111),
       ('Mysore',177,111),
       ('Hubli',177,111),
       ('Mangalore',177,111),
       ('Belgaum',177,111),
       ('Gulbarga',177,111),
       ('Dharwad',177,111),
       ('Bijapur',177,111),
       ('Shimoga',177,111),
       ('Bidar',177,111);